type Condition = {
  name: string;
  cause: string;
  urgency: string;
  nextSteps: string;
};

type Locale = "en" | "es" | "fr";

type ReportData = {
  userName: string;
  userEmail: string;
  gender: string;
  age: number;
  symptoms: string;
  conditions: Condition[];
  timestamp: Date;
  healthScore?: number;
  locale?: Locale;
};

const REPORT_STRINGS: Record<Locale, Record<string, string>> = {
  en: {
    title: "LaVida Health Report",
    subtitle: "AI-Powered Health Analysis",
    generatedOn: "Generated on",
    patientInfo: "Patient Information",
    name: "Name",
    email: "Email",
    gender: "Gender",
    age: "Age",
    years: "years",
    healthScore: "Health Score",
    goodStatus: "Good Health Status",
    fairStatus: "Fair - Consider Follow-up",
    needsAttention: "Needs Attention",
    reportedSymptoms: "Reported Symptoms",
    aiAnalysis: "AI Analysis",
    conditionsIdentified: "Conditions Identified",
    potentialCause: "Potential Cause",
    nextSteps: "Recommended Next Steps",
    disclaimer: "Medical Disclaimer:",
    disclaimerText:
      "This report is generated by an AI system and is for informational purposes only. It is not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. If you think you may have a medical emergency, call your doctor or emergency services immediately.",
    footer: "Generated by LaVida Health Buddy",
    popupBlocked:
      "Pop-up was blocked. Please allow pop-ups for this site to export your report.",
  },
  es: {
    title: "Informe de Salud LaVida",
    subtitle: "Analisis de Salud con IA",
    generatedOn: "Generado el",
    patientInfo: "Informacion del Paciente",
    name: "Nombre",
    email: "Correo",
    gender: "Genero",
    age: "Edad",
    years: "anios",
    healthScore: "Puntuacion de Salud",
    goodStatus: "Buena Salud",
    fairStatus: "Regular - Considere Seguimiento",
    needsAttention: "Requiere Atencion",
    reportedSymptoms: "Sintomas Reportados",
    aiAnalysis: "Analisis de IA",
    conditionsIdentified: "Condiciones Identificadas",
    potentialCause: "Causa Potencial",
    nextSteps: "Pasos Siguientes Recomendados",
    disclaimer: "Aviso Medico:",
    disclaimerText:
      "Este informe es generado por un sistema de IA y es solo para fines informativos. No es un sustituto del consejo medico profesional, diagnostico o tratamiento. Siempre consulte a su medico o profesional de salud calificado con preguntas sobre una condicion medica. Si cree que tiene una emergencia medica, llame a su medico o servicios de emergencia inmediatamente.",
    footer: "Generado por LaVida Health Buddy",
    popupBlocked:
      "Se bloqueo la ventana emergente. Permita ventanas emergentes para este sitio para exportar su informe.",
  },
  fr: {
    title: "Rapport de Sante LaVida",
    subtitle: "Analyse de Sante par IA",
    generatedOn: "Genere le",
    patientInfo: "Informations Patient",
    name: "Nom",
    email: "Email",
    gender: "Genre",
    age: "Age",
    years: "ans",
    healthScore: "Score de Sante",
    goodStatus: "Bonne Sante",
    fairStatus: "Passable - Suivi Recommande",
    needsAttention: "Necessite une Attention",
    reportedSymptoms: "Symptomes Signales",
    aiAnalysis: "Analyse IA",
    conditionsIdentified: "Conditions Identifiees",
    potentialCause: "Cause Potentielle",
    nextSteps: "Prochaines Etapes Recommandees",
    disclaimer: "Avertissement Medical:",
    disclaimerText:
      "Ce rapport est genere par un systeme d'IA et est uniquement a titre informatif. Il ne remplace pas les conseils medicaux professionnels, le diagnostic ou le traitement. Consultez toujours votre medecin ou un professionnel de sante qualifie pour toute question concernant une condition medicale. Si vous pensez avoir une emergency medicale, appelez immediatement votre medecin ou les services d'urgence.",
    footer: "Genere par LaVida Health Buddy",
    popupBlocked:
      "La fenetre popup a ete bloquee. Autorisez les popups pour ce site pour exporter votre rapport.",
  },
};

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function getUrgencyColor(urgency: string): string {
  switch (urgency) {
    case "critical":
      return "#dc2626";
    case "high":
      return "#ef4444";
    case "medium":
      return "#f59e0b";
    case "low":
      return "#16a34a";
    default:
      return "#6b7280";
  }
}

function getScoreStatus(
  score: number,
  s: Record<string, string>,
): string {
  if (score >= 70) return s.goodStatus;
  if (score >= 40) return s.fairStatus;
  return s.needsAttention;
}

export function generateHealthReport(data: ReportData): void {
  const locale = data.locale || "en";
  const s = REPORT_STRINGS[locale] || REPORT_STRINGS.en;
  const localeForDate =
    locale === "es" ? "es-ES" : locale === "fr" ? "fr-FR" : "en-US";

  const reportHTML = `
    <!DOCTYPE html>
    <html lang="${locale}">
    <head>
      <meta charset="UTF-8">
      <title>${escapeHtml(s.title)} - ${escapeHtml(data.userName)}</title>
      <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #1a1a1a; line-height: 1.6; padding: 40px; }
        .header { text-align: center; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #1A7F0A; }
        .logo { font-size: 32px; font-weight: bold; color: #1A7F0A; }
        .subtitle { color: #6b7280; margin-top: 8px; }
        .section { margin-bottom: 30px; }
        .section-title { font-size: 18px; font-weight: bold; color: #1A7F0A; margin-bottom: 15px; padding-bottom: 8px; border-bottom: 1px solid #e5e7eb; }
        .info-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 15px; margin-bottom: 20px; }
        .info-item { padding: 12px; background: #f9fafb; border-radius: 8px; }
        .info-label { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; }
        .info-value { font-size: 16px; font-weight: 600; margin-top: 4px; }
        .condition-card { border: 1px solid #e5e7eb; border-radius: 12px; padding: 20px; margin-bottom: 15px; page-break-inside: avoid; }
        .condition-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 12px; }
        .condition-name { font-size: 16px; font-weight: bold; }
        .urgency-badge { padding: 4px 12px; border-radius: 20px; font-size: 11px; font-weight: bold; color: white; text-transform: uppercase; }
        .condition-detail { margin-bottom: 10px; }
        .detail-label { font-size: 12px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 4px; }
        .detail-value { font-size: 14px; }
        .score-circle { width: 100px; height: 100px; border-radius: 50%; display: flex; align-items: center; justify-content: center; margin: 0 auto 15px; font-size: 32px; font-weight: bold; }
        .disclaimer { margin-top: 40px; padding: 20px; background: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; font-size: 12px; color: #92400e; }
        .footer { text-align: center; margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
        @media print { body { padding: 20px; } .no-print { display: none; } }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="logo">${escapeHtml(s.title)}</div>
        <div class="subtitle">${escapeHtml(s.subtitle)}</div>
        <div class="subtitle" style="margin-top: 5px;">${escapeHtml(s.generatedOn)} ${data.timestamp.toLocaleDateString(localeForDate, { weekday: "long", year: "numeric", month: "long", day: "numeric" })}</div>
      </div>

      <div class="section">
        <div class="section-title">${escapeHtml(s.patientInfo)}</div>
        <div class="info-grid">
          <div class="info-item">
            <div class="info-label">${escapeHtml(s.name)}</div>
            <div class="info-value">${escapeHtml(data.userName || "N/A")}</div>
          </div>
          <div class="info-item">
            <div class="info-label">${escapeHtml(s.email)}</div>
            <div class="info-value">${escapeHtml(data.userEmail || "N/A")}</div>
          </div>
          <div class="info-item">
            <div class="info-label">${escapeHtml(s.gender)}</div>
            <div class="info-value">${escapeHtml(data.gender)}</div>
          </div>
          <div class="info-item">
            <div class="info-label">${escapeHtml(s.age)}</div>
            <div class="info-value">${data.age} ${escapeHtml(s.years)}</div>
          </div>
        </div>
      </div>

      ${
        data.healthScore !== undefined
          ? `
      <div class="section">
        <div class="section-title">${escapeHtml(s.healthScore)}</div>
        <div class="score-circle" style="background: ${data.healthScore >= 70 ? "#dcfce7" : data.healthScore >= 40 ? "#fef3c7" : "#fee2e2"}; color: ${data.healthScore >= 70 ? "#16a34a" : data.healthScore >= 40 ? "#d97706" : "#dc2626"};">
          ${data.healthScore}
        </div>
        <p style="text-align: center; color: #6b7280; font-size: 14px;">
          ${escapeHtml(getScoreStatus(data.healthScore, s))}
        </p>
      </div>
      `
          : ""
      }

      <div class="section">
        <div class="section-title">${escapeHtml(s.reportedSymptoms)}</div>
        <p style="padding: 15px; background: #f9fafb; border-radius: 8px; font-size: 14px;">${escapeHtml(data.symptoms)}</p>
      </div>

      <div class="section">
        <div class="section-title">${escapeHtml(s.aiAnalysis)} - ${data.conditions.length} ${escapeHtml(s.conditionsIdentified)}</div>
        ${data.conditions
          .map(
            (condition, index) => `
          <div class="condition-card">
            <div class="condition-header">
              <span class="condition-name">${index + 1}. ${escapeHtml(condition.name)}</span>
              <span class="urgency-badge" style="background-color: ${getUrgencyColor(condition.urgency)};">${escapeHtml(condition.urgency)}</span>
            </div>
            <div class="condition-detail">
              <div class="detail-label">${escapeHtml(s.potentialCause)}</div>
              <div class="detail-value">${escapeHtml(condition.cause)}</div>
            </div>
            <div class="condition-detail">
              <div class="detail-label">${escapeHtml(s.nextSteps)}</div>
              <div class="detail-value">${escapeHtml(condition.nextSteps)}</div>
            </div>
          </div>
        `,
          )
          .join("")}
      </div>

      <div class="disclaimer">
        <strong>${escapeHtml(s.disclaimer)}</strong> ${escapeHtml(s.disclaimerText)}
      </div>

      <div class="footer">
        <p>${escapeHtml(s.footer)} | ${new Date().getFullYear()}</p>
      </div>
    </body>
    </html>
  `;

  const printWindow = window.open("", "_blank");
  if (printWindow) {
    printWindow.document.write(reportHTML);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
    }, 500);
  } else {
    alert(s.popupBlocked);
  }
}
